linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - bodyclose
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - gocyclo
    - gocognit
    - godot
    - gofumpt
    - misspell
    - unparam
    - unconvert
    - prealloc
    - exportloopref
    - gocritic
    - gosec
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  govet:
    check-shadowing: true

  errcheck:
    check-type-assertions: true
    check-blank: true

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentedOutCode

  gosec:
    excludes:
      - G104 # Audit errors not checked (we use errcheck)

  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - testdata
    - examples
  skip-files:
    - ".*\\.pb\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
